# Copyright ? 2019 Intel Corporation
# #
# # Licensed under the Apache License, Version 2.0 (the "License");
# # you may not use this file except in compliance with the License.
# # You may obtain a copy of the License at
# #
# #       http://www.apache.org/licenses/LICENSE-2.0
# #
# # Unless required by applicable law or agreed to in writing, software
# # distributed under the License is distributed on an "AS IS" BASIS,
# # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# # See the License for the specific language governing permissions and
# # limitations under the License.

metadata:
  name: keycloak
  namespace: default
image:
    repository: jboss/keycloak
    tag: 6.0.1
    pullPolicy: IfNotPresent  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
resources: {}
env:
- name: KEYCLOAK_USER
  value: "admin"
- name: KEYCLOAK_PASSWORD
  value: "admin"
- name: PROXY_ADDRESS_FORWARDING
  value: "true"
readinessProbe:
  httpGet:
    path: /auth/realms/master
    port: 8080
  failureThreshold: 10
  initialDelaySeconds: 30
livenessProbe:
  httpGet:
    path: /auth/realms/master
    port: 8080
  initialDelaySeconds: 60
ports:
- name: http
  containerPort: 8080
- name: https
  containerPort: 8443

Service:
  metadata:
    name: keycloak
    labels:
      app: keycloak
  spec:
    type: LoadBalancer
    ports:
    - name: http
      port: 8080
    selector:
      app: keycloak
