---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: "controller01"
  ip: "10.10.10.3"
  memory: 8192
  cpus: 2
  roles:
    - kube-master
    - etcd
    - ovn-central
- name: "controller02"
  ip: "10.10.10.4"
  memory: 8192
  cpus: 2
  roles:
    - kube-master
    - etcd
    - ovn-controller
- name: "controller03"
  ip: "10.10.10.5"
  memory: 8192
  cpus: 2
  roles:
    - kube-master
    - etcd
    - ovn-controller
- name: "compute01"
  ip: "10.10.10.6"
  memory: 32768
  cpus: 16
  volumes:
    - name: sdb
      size: 50
      mount: /var/lib/docker/
  roles:
    - kube-node
    - ovn-controller
    - virtlet
- name: "compute02"
  ip: "10.10.10.7"
  memory: 8192
  cpus: 4
  roles:
    - kube-node
    - ovn-controller
