apiVersion: k8s.plugin.opnfv.org/v1alpha1
kind: ProviderNetwork
metadata:
  name: unprotected-private-net
spec:
  cniType : ovn4nfv
  ipv4Subnets:
  - name: subnet1
    subnet: 192.168.10.0/24
    gateway: 192.168.10.1/24
  providerNetType: VLAN
  vlan:
    vlanId: "100"
    providerInterfaceName: eth1
    logicalInterfaceName: eth1.100
    vlanNodeSelector: specific
    nodeLabelList:
    - kubernetes.io/hostname=localhost
