# Copyright 2019 Intel Corporation, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

debugEnabled: false

# application configuration is via config files

# default number of instances
replicaCount: 1

nodeSelector: {}

affinity: {}

#Mongo chart overrides for emco
mongo:
  nameOverride: emco-mongo
  service:
    name: emco-mongo
    internalPort: 27017
  nfsprovisionerPrefix: emco
  sdnctlPrefix: emco
  persistence:
    mountSubPath: emco/mongo/data
    enabled: true
  disableNfsProvisioner: true

#etcd chart overrides for k8splugin
etcd:
  nameOverride: emco-etcd
  service:
    name: emco-etcd
  persistence:
    mountSubPath: emco/etcd/data
    enabled: true

# Configure resource requests and limits
flavor: large
resources:
  small:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 10m
      memory: 10Mi
  large:
    limits:
      cpu: 400m
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 100Mi
  unlimited: {}
