---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- hosts: kube-master
  tasks:
    - name: Load kud variables
      include_vars:
        file: kud-vars.yml

    - name: uninstall multicloud onap helm chart
      shell: |
        pushd /opt/multicloud/deployments/helm/onap4k8s
        helm delete --purge multicloud-onap8ks
        make clean
        make repo-stop
        kubectl delete ns onap4k8s-ns
        popd
      args:
        executable: /bin/bash

    - name: clean multicloud-k8s path
      file:
        state: absent
        path: /opt/multicloud

