---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- import_playbook: preconfigure-sriov.yml

- hosts: localhost
  become: yes
  tasks:
    - debug:
        var: SRIOV_NODE
    - name: Apply Multus
      shell: "/usr/local/bin/kubectl apply -f {{ playbook_dir }}/../images/multus-daemonset.yml"
      when: SRIOV_NODE
    - name: Apply SRIOV CNI
      shell: "/usr/local/bin/kubectl apply -f {{ playbook_dir }}/../images/sriov-cni.yml"
      when: SRIOV_NODE
    - name: Apply SRIOV DaemonSet
      shell: "/usr/local/bin/kubectl apply -f {{ playbook_dir }}/../images/sriov-daemonset.yml"
      when: SRIOV_NODE
    - name: Apply SRIOV Network Attachment definition
      shell: "/usr/local/bin/kubectl apply -f {{ playbook_dir }}/sriov-nad.yml"
      when: SRIOV_NODE
