---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- hosts: kube-master
  tasks:
    - name: Load kud variables
      include_vars:
        file: kud-vars.yml

    - name: Getting onap4k8s code in /opt folder
      git:
        repo: 'https://github.com/onap/multicloud-k8s.git'
        dest: /opt/multicloud

    - name: install make package for ubuntu systems
      apt: name=make state=present update_cache=yes
      when: ansible_distribution == "Ubuntu"

    - name: install make package for centos systems
      yum: name=make state=present update_cache=yes
      when: ansible_distribution == "CentOS"

    - name: Change the onap4k8s directory and run the command make all
      command: /usr/bin/make all
      register: make_all
      args:
        chdir: /opt/multicloud/deployments/helm/onap4k8s

    - debug:
        var: make_all.stdout_lines

    - name: Create onap4k8s-ns namespace
      shell: "/usr/local/bin/kubectl create namespace onap4k8s-ns"
      ignore_errors: True

    - name: Create pod security policy role bindings
      shell: "/usr/local/bin/kubectl -n onap4k8s-ns create rolebinding psp:default:privileged --clusterrole=psp:privileged --serviceaccount=onap4k8s-ns:default"
      ignore_errors: True

    - name: Change the onap4k8s directory and run the command helm install
      command: /usr/local/bin/helm install --namespace onap4k8s-ns --set service.type=NodePort multicloud-onap8ks dist/packages/multicloud-k8s-5.0.0.tgz
      register: helm_install
      args:
        chdir: /opt/multicloud/deployments/helm/onap4k8s

    - debug:
        var: helm_install.stdout_lines
