---
# The mitogen module used in kubespray requires /usr/bin/python on
# the nodes. On some distributions, the default version of
# python is python3.
#
# When not present a failure message similar to "bash:
# /usr/bin/python: No such file or directory" will be reported.
#
# Note the use of "strategy: linear" below to temporarily bypass
# mitogen.
#
- name: Set /usr/bin/python
  hosts: k8s-cluster
  strategy: linear
  tasks:
    - name: Install python2 on Ubuntu
      # As of mitogen 0.2.9, mitogen reports that performance on
      # python3 is significantly worse than on python2, so stick with
      # python2.
      package:
        name: python
        state: present
      when: ansible_distribution == "Ubuntu"
    - name: Set /usr/bin/python to link to python3
      # python2-dnf is needed by kubespray and not available, so use
      # python3.
      alternatives:
        name: python
        path: /usr/bin/python3
      when: ansible_distribution == "CentOS"
