// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controller.proto

package controller

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SitesRequest struct {
	IntentGroup          string   `protobuf:"bytes,1,opt,name=intent_group,json=intentGroup,proto3" json:"intent_group,omitempty"`
	AppContext           string   `protobuf:"bytes,2,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SitesRequest) Reset()         { *m = SitesRequest{} }
func (m *SitesRequest) String() string { return proto.CompactTextString(m) }
func (*SitesRequest) ProtoMessage()    {}
func (*SitesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{0}
}

func (m *SitesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SitesRequest.Unmarshal(m, b)
}
func (m *SitesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SitesRequest.Marshal(b, m, deterministic)
}
func (m *SitesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SitesRequest.Merge(m, src)
}
func (m *SitesRequest) XXX_Size() int {
	return xxx_messageInfo_SitesRequest.Size(m)
}
func (m *SitesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SitesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SitesRequest proto.InternalMessageInfo

func (m *SitesRequest) GetIntentGroup() string {
	if m != nil {
		return m.IntentGroup
	}
	return ""
}

func (m *SitesRequest) GetAppContext() string {
	if m != nil {
		return m.AppContext
	}
	return ""
}

type SitesResponse struct {
	AppContextUpdated    bool     `protobuf:"varint,1,opt,name=app_context_updated,json=appContextUpdated,proto3" json:"app_context_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SitesResponse) Reset()         { *m = SitesResponse{} }
func (m *SitesResponse) String() string { return proto.CompactTextString(m) }
func (*SitesResponse) ProtoMessage()    {}
func (*SitesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{1}
}

func (m *SitesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SitesResponse.Unmarshal(m, b)
}
func (m *SitesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SitesResponse.Marshal(b, m, deterministic)
}
func (m *SitesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SitesResponse.Merge(m, src)
}
func (m *SitesResponse) XXX_Size() int {
	return xxx_messageInfo_SitesResponse.Size(m)
}
func (m *SitesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SitesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SitesResponse proto.InternalMessageInfo

func (m *SitesResponse) GetAppContextUpdated() bool {
	if m != nil {
		return m.AppContextUpdated
	}
	return false
}

type UpdateFeaturesRequest struct {
	ClusterName          string   `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFeaturesRequest) Reset()         { *m = UpdateFeaturesRequest{} }
func (m *UpdateFeaturesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFeaturesRequest) ProtoMessage()    {}
func (*UpdateFeaturesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{2}
}

func (m *UpdateFeaturesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFeaturesRequest.Unmarshal(m, b)
}
func (m *UpdateFeaturesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFeaturesRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFeaturesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFeaturesRequest.Merge(m, src)
}
func (m *UpdateFeaturesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFeaturesRequest.Size(m)
}
func (m *UpdateFeaturesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFeaturesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFeaturesRequest proto.InternalMessageInfo

func (m *UpdateFeaturesRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

type UpdateFeaturesResponse struct {
	FeaturesStored       bool     `protobuf:"varint,1,opt,name=features_stored,json=featuresStored,proto3" json:"features_stored,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFeaturesResponse) Reset()         { *m = UpdateFeaturesResponse{} }
func (m *UpdateFeaturesResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFeaturesResponse) ProtoMessage()    {}
func (*UpdateFeaturesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{3}
}

func (m *UpdateFeaturesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFeaturesResponse.Unmarshal(m, b)
}
func (m *UpdateFeaturesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFeaturesResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFeaturesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFeaturesResponse.Merge(m, src)
}
func (m *UpdateFeaturesResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFeaturesResponse.Size(m)
}
func (m *UpdateFeaturesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFeaturesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFeaturesResponse proto.InternalMessageInfo

func (m *UpdateFeaturesResponse) GetFeaturesStored() bool {
	if m != nil {
		return m.FeaturesStored
	}
	return false
}

func init() {
	proto.RegisterType((*SitesRequest)(nil), "SitesRequest")
	proto.RegisterType((*SitesResponse)(nil), "SitesResponse")
	proto.RegisterType((*UpdateFeaturesRequest)(nil), "UpdateFeaturesRequest")
	proto.RegisterType((*UpdateFeaturesResponse)(nil), "UpdateFeaturesResponse")
}

func init() { proto.RegisterFile("controller.proto", fileDescriptor_ed7f10298fa1d90f) }

var fileDescriptor_ed7f10298fa1d90f = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xb1, 0x4f, 0x02, 0x31,
	0x14, 0xc6, 0x39, 0x07, 0xa3, 0xef, 0xe0, 0xd4, 0x1a, 0x91, 0xb0, 0xa8, 0x5d, 0x74, 0xea, 0xa0,
	0x9b, 0x8b, 0x31, 0x24, 0xba, 0x39, 0x1c, 0x71, 0x6e, 0x2a, 0x3c, 0x0d, 0xc9, 0xd1, 0x3e, 0xdb,
	0xd7, 0xc4, 0xd5, 0xff, 0xdc, 0xd0, 0x1e, 0xc2, 0x11, 0xb6, 0xe6, 0xd7, 0xbe, 0x2f, 0xbf, 0xef,
	0x15, 0x4e, 0x67, 0xce, 0xb2, 0x77, 0x4d, 0x83, 0x5e, 0x91, 0x77, 0xec, 0x64, 0x0d, 0xfd, 0xe9,
	0x82, 0x31, 0xd4, 0xf8, 0x1d, 0x31, 0xb0, 0xb8, 0x81, 0xfe, 0xc2, 0x32, 0x5a, 0xd6, 0x5f, 0xde,
	0x45, 0x1a, 0x15, 0xd7, 0xc5, 0xdd, 0x71, 0x5d, 0x66, 0xf6, 0xba, 0x42, 0xe2, 0x0a, 0x4a, 0x43,
	0xa4, 0x57, 0x51, 0xf8, 0xc3, 0xa3, 0x83, 0xf4, 0x02, 0x0c, 0xd1, 0x24, 0x13, 0xf9, 0x04, 0x83,
	0x36, 0x33, 0x90, 0xb3, 0x01, 0x85, 0x82, 0xf3, 0xad, 0x09, 0x1d, 0x69, 0x6e, 0x18, 0xe7, 0x29,
	0xfb, 0xa8, 0x3e, 0xdb, 0x4c, 0xbe, 0xe7, 0x0b, 0xf9, 0x08, 0x17, 0xf9, 0xf8, 0x82, 0x86, 0xa3,
	0xef, 0xd8, 0xcd, 0x9a, 0x18, 0x18, 0xbd, 0xb6, 0x66, 0x89, 0x6b, 0xbb, 0x96, 0xbd, 0x99, 0x25,
	0xca, 0x67, 0x18, 0xee, 0xce, 0xb6, 0x16, 0xb7, 0x70, 0xf2, 0xd9, 0x32, 0x1d, 0xd8, 0xf9, 0x7f,
	0x83, 0x6a, 0x8d, 0xa7, 0x89, 0xde, 0xff, 0x16, 0x00, 0x9b, 0x45, 0x09, 0x05, 0x65, 0x4e, 0x4c,
	0xa5, 0xc4, 0x40, 0x6d, 0x2f, 0x6c, 0x5c, 0xa9, 0x4e, 0x57, 0xd9, 0x13, 0x13, 0xa8, 0xba, 0x06,
	0x62, 0xa8, 0xf6, 0xd6, 0x19, 0x5f, 0xaa, 0xfd, 0xaa, 0xb2, 0xf7, 0x71, 0x98, 0xbe, 0xe7, 0xe1,
	0x2f, 0x00, 0x00, 0xff, 0xff, 0x13, 0xae, 0x96, 0x9f, 0xb2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControllerClient interface {
	// Placement Controllers
	UpdateSites(ctx context.Context, in *SitesRequest, opts ...grpc.CallOption) (*SitesResponse, error)
	// HPA Placement Controller
	UpdateFeatures(ctx context.Context, in *UpdateFeaturesRequest, opts ...grpc.CallOption) (*UpdateFeaturesResponse, error)
}

type controllerClient struct {
	cc *grpc.ClientConn
}

func NewControllerClient(cc *grpc.ClientConn) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) UpdateSites(ctx context.Context, in *SitesRequest, opts ...grpc.CallOption) (*SitesResponse, error) {
	out := new(SitesResponse)
	err := c.cc.Invoke(ctx, "/controller/UpdateSites", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) UpdateFeatures(ctx context.Context, in *UpdateFeaturesRequest, opts ...grpc.CallOption) (*UpdateFeaturesResponse, error) {
	out := new(UpdateFeaturesResponse)
	err := c.cc.Invoke(ctx, "/controller/UpdateFeatures", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
type ControllerServer interface {
	// Placement Controllers
	UpdateSites(context.Context, *SitesRequest) (*SitesResponse, error)
	// HPA Placement Controller
	UpdateFeatures(context.Context, *UpdateFeaturesRequest) (*UpdateFeaturesResponse, error)
}

// UnimplementedControllerServer can be embedded to have forward compatible implementations.
type UnimplementedControllerServer struct {
}

func (*UnimplementedControllerServer) UpdateSites(ctx context.Context, req *SitesRequest) (*SitesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSites not implemented")
}
func (*UnimplementedControllerServer) UpdateFeatures(ctx context.Context, req *UpdateFeaturesRequest) (*UpdateFeaturesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFeatures not implemented")
}

func RegisterControllerServer(s *grpc.Server, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_UpdateSites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SitesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).UpdateSites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller/UpdateSites",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).UpdateSites(ctx, req.(*SitesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_UpdateFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFeaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).UpdateFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller/UpdateFeatures",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).UpdateFeatures(ctx, req.(*UpdateFeaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Controller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateSites",
			Handler:    _Controller_UpdateSites_Handler,
		},
		{
			MethodName: "UpdateFeatures",
			Handler:    _Controller_UpdateFeatures_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller.proto",
}
