// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controller.proto

package controller

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SitesRequest struct {
	IntentGroup          string   `protobuf:"bytes,1,opt,name=intent_group,json=intentGroup,proto3" json:"intent_group,omitempty"`
	RbName               string   `protobuf:"bytes,2,opt,name=rb_name,json=rbName,proto3" json:"rb_name,omitempty"`
	RbVersion            string   `protobuf:"bytes,3,opt,name=rb_version,json=rbVersion,proto3" json:"rb_version,omitempty"`
	ProfileName          string   `protobuf:"bytes,4,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	ProjectName          string   `protobuf:"bytes,5,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	AppContext           string   `protobuf:"bytes,6,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SitesRequest) Reset()         { *m = SitesRequest{} }
func (m *SitesRequest) String() string { return proto.CompactTextString(m) }
func (*SitesRequest) ProtoMessage()    {}
func (*SitesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{0}
}

func (m *SitesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SitesRequest.Unmarshal(m, b)
}
func (m *SitesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SitesRequest.Marshal(b, m, deterministic)
}
func (m *SitesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SitesRequest.Merge(m, src)
}
func (m *SitesRequest) XXX_Size() int {
	return xxx_messageInfo_SitesRequest.Size(m)
}
func (m *SitesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SitesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SitesRequest proto.InternalMessageInfo

func (m *SitesRequest) GetIntentGroup() string {
	if m != nil {
		return m.IntentGroup
	}
	return ""
}

func (m *SitesRequest) GetRbName() string {
	if m != nil {
		return m.RbName
	}
	return ""
}

func (m *SitesRequest) GetRbVersion() string {
	if m != nil {
		return m.RbVersion
	}
	return ""
}

func (m *SitesRequest) GetProfileName() string {
	if m != nil {
		return m.ProfileName
	}
	return ""
}

func (m *SitesRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *SitesRequest) GetAppContext() string {
	if m != nil {
		return m.AppContext
	}
	return ""
}

type SitesResponse struct {
	AppContextUpdated    bool     `protobuf:"varint,1,opt,name=app_context_updated,json=appContextUpdated,proto3" json:"app_context_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SitesResponse) Reset()         { *m = SitesResponse{} }
func (m *SitesResponse) String() string { return proto.CompactTextString(m) }
func (*SitesResponse) ProtoMessage()    {}
func (*SitesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{1}
}

func (m *SitesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SitesResponse.Unmarshal(m, b)
}
func (m *SitesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SitesResponse.Marshal(b, m, deterministic)
}
func (m *SitesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SitesResponse.Merge(m, src)
}
func (m *SitesResponse) XXX_Size() int {
	return xxx_messageInfo_SitesResponse.Size(m)
}
func (m *SitesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SitesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SitesResponse proto.InternalMessageInfo

func (m *SitesResponse) GetAppContextUpdated() bool {
	if m != nil {
		return m.AppContextUpdated
	}
	return false
}

type StoreFeaturesRequest struct {
	ClusterName          string     `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Features             []*Feature `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StoreFeaturesRequest) Reset()         { *m = StoreFeaturesRequest{} }
func (m *StoreFeaturesRequest) String() string { return proto.CompactTextString(m) }
func (*StoreFeaturesRequest) ProtoMessage()    {}
func (*StoreFeaturesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{2}
}

func (m *StoreFeaturesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreFeaturesRequest.Unmarshal(m, b)
}
func (m *StoreFeaturesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreFeaturesRequest.Marshal(b, m, deterministic)
}
func (m *StoreFeaturesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreFeaturesRequest.Merge(m, src)
}
func (m *StoreFeaturesRequest) XXX_Size() int {
	return xxx_messageInfo_StoreFeaturesRequest.Size(m)
}
func (m *StoreFeaturesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreFeaturesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreFeaturesRequest proto.InternalMessageInfo

func (m *StoreFeaturesRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *StoreFeaturesRequest) GetFeatures() []*Feature {
	if m != nil {
		return m.Features
	}
	return nil
}

type Feature struct {
	Feature              string   `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{3}
}

func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (m *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(m, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetFeature() string {
	if m != nil {
		return m.Feature
	}
	return ""
}

type StoreFeaturesResponse struct {
	FeaturesStored       bool     `protobuf:"varint,1,opt,name=features_stored,json=featuresStored,proto3" json:"features_stored,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreFeaturesResponse) Reset()         { *m = StoreFeaturesResponse{} }
func (m *StoreFeaturesResponse) String() string { return proto.CompactTextString(m) }
func (*StoreFeaturesResponse) ProtoMessage()    {}
func (*StoreFeaturesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{4}
}

func (m *StoreFeaturesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreFeaturesResponse.Unmarshal(m, b)
}
func (m *StoreFeaturesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreFeaturesResponse.Marshal(b, m, deterministic)
}
func (m *StoreFeaturesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreFeaturesResponse.Merge(m, src)
}
func (m *StoreFeaturesResponse) XXX_Size() int {
	return xxx_messageInfo_StoreFeaturesResponse.Size(m)
}
func (m *StoreFeaturesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreFeaturesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoreFeaturesResponse proto.InternalMessageInfo

func (m *StoreFeaturesResponse) GetFeaturesStored() bool {
	if m != nil {
		return m.FeaturesStored
	}
	return false
}

func init() {
	proto.RegisterType((*SitesRequest)(nil), "SitesRequest")
	proto.RegisterType((*SitesResponse)(nil), "SitesResponse")
	proto.RegisterType((*StoreFeaturesRequest)(nil), "StoreFeaturesRequest")
	proto.RegisterType((*Feature)(nil), "Feature")
	proto.RegisterType((*StoreFeaturesResponse)(nil), "StoreFeaturesResponse")
}

func init() { proto.RegisterFile("controller.proto", fileDescriptor_ed7f10298fa1d90f) }

var fileDescriptor_ed7f10298fa1d90f = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcd, 0x4e, 0xeb, 0x30,
	0x10, 0x85, 0xfb, 0x73, 0x6f, 0x7f, 0x26, 0x6d, 0xef, 0xc5, 0x50, 0x88, 0x2a, 0x21, 0x8a, 0x41,
	0xa2, 0x2b, 0x2f, 0xca, 0x03, 0x50, 0x09, 0x09, 0x76, 0x2c, 0x52, 0xc1, 0xd6, 0x4a, 0xda, 0x29,
	0x0a, 0x4a, 0x63, 0x63, 0x3b, 0x88, 0x15, 0xcf, 0xc8, 0x23, 0xa1, 0xd8, 0x4e, 0x7f, 0x50, 0x97,
	0xfd, 0xe6, 0xcc, 0xe9, 0x9c, 0xe3, 0xc0, 0xff, 0x85, 0xc8, 0x8d, 0x12, 0x59, 0x86, 0x8a, 0x49,
	0x25, 0x8c, 0xa0, 0xdf, 0x75, 0xe8, 0xcd, 0x53, 0x83, 0x3a, 0xc2, 0xf7, 0x02, 0xb5, 0x21, 0x97,
	0xd0, 0x4b, 0x73, 0x83, 0xb9, 0xe1, 0xaf, 0x4a, 0x14, 0x32, 0xac, 0x8f, 0xeb, 0x93, 0x6e, 0x14,
	0x38, 0xf6, 0x58, 0x22, 0x72, 0x06, 0x6d, 0x95, 0xf0, 0x3c, 0x5e, 0x63, 0xd8, 0xb0, 0xd3, 0x96,
	0x4a, 0x9e, 0xe2, 0x35, 0x92, 0x73, 0x00, 0x95, 0xf0, 0x0f, 0x54, 0x3a, 0x15, 0x79, 0xd8, 0xb4,
	0xb3, 0xae, 0x4a, 0x5e, 0x1c, 0x28, 0xad, 0xa5, 0x12, 0xab, 0x34, 0x43, 0xb7, 0xfc, 0xc7, 0x59,
	0x7b, 0x66, 0x1d, 0x9c, 0xe4, 0x0d, 0x17, 0xc6, 0x49, 0xfe, 0x6e, 0x24, 0x25, 0xb3, 0x92, 0x0b,
	0x08, 0x62, 0x29, 0x79, 0x99, 0x04, 0x3f, 0x4d, 0xd8, 0xb2, 0x0a, 0x88, 0xa5, 0xbc, 0x77, 0x84,
	0xde, 0x41, 0xdf, 0x27, 0xd2, 0x52, 0xe4, 0x1a, 0x09, 0x83, 0xe3, 0x9d, 0x0d, 0x5e, 0xc8, 0x65,
	0x6c, 0x70, 0x69, 0x93, 0x75, 0xa2, 0xa3, 0xed, 0xe6, 0xb3, 0x1b, 0x50, 0x0e, 0x27, 0x73, 0x23,
	0x14, 0x3e, 0x60, 0x6c, 0x0a, 0xb5, 0x57, 0xcd, 0x22, 0x2b, 0xb4, 0x41, 0xe5, 0x8e, 0xf3, 0xd5,
	0x78, 0x66, 0x8f, 0xbb, 0x86, 0xce, 0xca, 0x6f, 0x85, 0x8d, 0x71, 0x73, 0x12, 0x4c, 0x3b, 0xcc,
	0xdb, 0x44, 0x9b, 0x09, 0xbd, 0x82, 0xb6, 0x87, 0x24, 0x84, 0xb6, 0xc7, 0xde, 0xae, 0xfa, 0x49,
	0x67, 0x30, 0xfc, 0x75, 0x85, 0x8f, 0x73, 0x03, 0xff, 0x2a, 0x27, 0xae, 0x4b, 0x45, 0x15, 0x65,
	0x50, 0x61, 0xbb, 0xb7, 0x9c, 0x7e, 0x01, 0x6c, 0xdf, 0x9b, 0x30, 0x08, 0x5c, 0x40, 0x5b, 0x0e,
	0xe9, 0xb3, 0xdd, 0x67, 0x1f, 0x0d, 0xd8, 0x5e, 0x67, 0xb4, 0x46, 0x66, 0xd0, 0xdf, 0xfb, 0x7f,
	0x32, 0x64, 0x87, 0x5a, 0x19, 0x9d, 0xb2, 0x83, 0x67, 0xd2, 0x5a, 0xd2, 0xb2, 0x9f, 0xd8, 0xed,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xf2, 0x1c, 0xb3, 0x76, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControllerClient interface {
	// Placement Controllers
	UpdateSites(ctx context.Context, in *SitesRequest, opts ...grpc.CallOption) (*SitesResponse, error)
	// HPA Placement Controller
	StoreFeatures(ctx context.Context, in *StoreFeaturesRequest, opts ...grpc.CallOption) (*StoreFeaturesResponse, error)
}

type controllerClient struct {
	cc *grpc.ClientConn
}

func NewControllerClient(cc *grpc.ClientConn) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) UpdateSites(ctx context.Context, in *SitesRequest, opts ...grpc.CallOption) (*SitesResponse, error) {
	out := new(SitesResponse)
	err := c.cc.Invoke(ctx, "/controller/UpdateSites", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) StoreFeatures(ctx context.Context, in *StoreFeaturesRequest, opts ...grpc.CallOption) (*StoreFeaturesResponse, error) {
	out := new(StoreFeaturesResponse)
	err := c.cc.Invoke(ctx, "/controller/StoreFeatures", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
type ControllerServer interface {
	// Placement Controllers
	UpdateSites(context.Context, *SitesRequest) (*SitesResponse, error)
	// HPA Placement Controller
	StoreFeatures(context.Context, *StoreFeaturesRequest) (*StoreFeaturesResponse, error)
}

// UnimplementedControllerServer can be embedded to have forward compatible implementations.
type UnimplementedControllerServer struct {
}

func (*UnimplementedControllerServer) UpdateSites(ctx context.Context, req *SitesRequest) (*SitesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSites not implemented")
}
func (*UnimplementedControllerServer) StoreFeatures(ctx context.Context, req *StoreFeaturesRequest) (*StoreFeaturesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreFeatures not implemented")
}

func RegisterControllerServer(s *grpc.Server, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_UpdateSites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SitesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).UpdateSites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller/UpdateSites",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).UpdateSites(ctx, req.(*SitesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_StoreFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreFeaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).StoreFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller/StoreFeatures",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).StoreFeatures(ctx, req.(*StoreFeaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Controller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateSites",
			Handler:    _Controller_UpdateSites_Handler,
		},
		{
			MethodName: "StoreFeatures",
			Handler:    _Controller_StoreFeatures_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller.proto",
}
