apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sriov-network-operator.serviceAccountName" . }}
  labels:
    {{- include "sriov-network-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-network-config-daemon
  labels:
    {{- include "sriov-network-operator.labels" . | nindent 4 }}
