apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: host-device-{{ .Values.global.unprotectedNetPortVfw }}
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "host-device",
      "device": "{{ .Values.global.unprotectedNetPortVfw }}"
    }'

---
  
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: host-device-{{ .Values.global.unprotectedNetPortVpg }}
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "host-device",
      "device": "{{ .Values.global.unprotectedNetPortVpg }}"
    }'
