apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "packetgen.fullname" . }}
  labels:
    release: {{ .Release.Name }}
    app: {{ include "packetgen.name" . }}
    chart: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "packetgen.name" .}}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "packetgen.name" .}}
        release: {{ .Release.Name }}
      annotations:
        app: {{ include "packetgen.name" . }}
        release: {{ .Release.Name }}
        VirtletLibvirtCPUSetting: |
          mode: host-model
        VirtletCloudInitUserData: |
          ssh_pwauth: True
          users:
          - name: admin
            gecos: User
            primary-group: admin
            groups: users
            sudo: ALL=(ALL) NOPASSWD:ALL
            lock_passwd: false
            passwd: "$6$rounds=4096$QA5OCKHTE41$jRACivoPMJcOjLRgxl3t.AMfU7LhCFwOWv2z66CQX.TSxBy50JoYtycJXSPr2JceG.8Tq/82QN9QYt3euYEZW/"
          runcmd:
            - export demo_artifacts_version={{ .Values.global.demoArtifactsVersion }}
            - export vfw_private_ip_0={{ .Values.global.vfwPrivateIp0 }}
            - export vsn_private_ip_0={{ .Values.global.vsnPrivateIp0 }}
            - export protected_net_cidr={{ .Values.global.protectedNetCidr }}
            - export dcae_collector_ip={{ .Values.global.dcaeCollectorIp }}
            - export dcae_collector_port={{ .Values.global.dcaeCollectorPort }}
            - export protected_net_gw={{ .Values.global.protectedNetGw }}
            - export protected_private_net_cidr={{ .Values.global.protectedPrivateNetCidr }}
            - wget -O - https://git.onap.org/multicloud/k8s/plain/kud/tests/vFW/packetgen | sudo -E bash
        VirtletRootVolumeSize: 5Gi
        kubernetes.io/target-runtime: virtlet.cloud
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: extraRuntime
                operator: In
                values:
                - virtlet
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        tty: true
        stdin: true
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
