---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "cmk.fullname" . }}
  labels:
    app: {{ include "cmk.fullname" . }}
spec:
  selector:
    matchLabels:
      name: {{ include "cmk.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ include "cmk.fullname" . }}
    spec:
      {{- if not .Values.hosts.all }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            {{- range splitList "," .Values.hosts.list }}
            - matchFields:
              - key: metadata.name
                operator: In
                values:
                - {{ . }}
            {{- end }}
      {{- end }}
      serviceAccountName: {{ include "cmk.fullname" . }}
      tolerations:
      - key: cmk
        operator: Exists
      containers:
      - name: reconcile
#        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        image: mjace/cmk:v1.4.0
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: CMK_RECONCILE_SLEEP_TIME
          value: '60'
        - name: CMK_PROC_FS
          value: /proc
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        command: ["/bin/bash", "-c"]
        args:
        - "/cmk/cmk.py isolate --pool=infra /cmk/cmk.py -- reconcile --interval=$CMK_RECONCILE_SLEEP_TIME --publish"
        volumeMounts:
        - mountPath: /proc
          name: host-proc
          readOnly:  false
        - mountPath: /etc/cmk
          name: cmk-conf-dir
        - mountPath: /opt/bin
          name: cmk-install-dir
      - name: nodereport
        #image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        image: mjace/cmk:v1.4.0
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: CMK_NODE_REPORT_SLEEP_TIME
          value: '60'
        - name: CMK_PROC_FS
          value: /proc
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        command: ["/bin/bash", "-c"]
        args:
        - "/cmk/cmk.py isolate --pool=infra /cmk/cmk.py -- node-report --interval=$CMK_NODE_REPORT_SLEEP_TIME --publish"
        volumeMounts:
        - mountPath: /proc
          name: host-proc
          readOnly: false
        - mountPath: /etc/cmk
          name: cmk-conf-dir
        - mountPath: /opt/bin
          name: cmk-install-dir
      initContainers:
      - name: init
        #image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        image: mjace/cmk:v1.4.0
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: CMK_PROC_FS
          value: "/proc"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        command: ["/bin/bash", "-c"]
        args:
        - "/cmk/cmk.py init --conf-dir=/etc/cmk --exclusive-mode={{ .Values.exclusiveMode }} --num-exclusive-cores={{ .Values.numExclusiveCores }} --shared-mode={{ .Values.sharedMode }} --num-shared-cores={{ .Values.numSharedCores }}"
        volumeMounts:
        - mountPath: /proc
          name: host-proc
          readOnly: false
        - mountPath: /etc/cmk
          name: cmk-conf-dir
        - mountPath: /opt/bin
          name: cmk-install-dir
      - name: discover
        #image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        image: mjace/cmk:v1.4.0
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: CMK_PROC_FS
          value: /proc
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        command: ["/bin/bash", "-c"]
        args:
        - "until [ -d /etc/cmk ]; do sleep 1; done; /cmk/cmk.py discover"
        volumeMounts:
        - mountPath: /proc
          name: host-proc
          readOnly: false
        - mountPath: /etc/cmk
          name: cmk-conf-dir
        - mountPath: /opt/bin
          name: cmk-install-dir
      - name: install
        #image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        image: mjace/cmk:v1.4.0
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: CMK_PROC_FS
          value: /proc
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        command: ["/bin/bash", "-c"]
        args:
        - "/cmk/cmk.py install"
        volumeMounts:
        - mountPath: /proc
          name: host-proc
          readOnly: false
        - mountPath: /etc/cmk
          name: cmk-conf-dir
        - mountPath: /opt/bin
          name: cmk-install-dir
      #restartPolicy: Never 
      volumes:
      - hostPath:
          path: /proc
          type: ""
        name: host-proc
      - hostPath:
          path: /etc/cmk
          type: ""
        name: cmk-conf-dir
      - hostPath:
          path: /opt/bin
          type: ""
        name: cmk-install-dir
