---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "cmk.fullname" . }}-third-party-resource-controller
rules:
- apiGroups: ["cmk.intel.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["thirdpartyresources", "thirdpartyresources.extensions"]
  verbs: ["*"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "cmk.fullname" . }}-custom-resource-definition-controller
rules:
- apiGroups: ["intel.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions", "customresourcedefinitions.extensions"]
  verbs: ["*"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "cmk.fullname" . }}-daemonset-controller
rules:
- apiGroups: ["extensions"]
  resources: ["daemonsets", "daemonsets.extensions"]
  verbs: ["*"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "cmk.fullname" . }}-version-controller
rules:
  - nonResourceURLs: ["*"]
    verbs:
      - get
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "cmk.fullname" . }}-webhook-installer
rules:
- apiGroups: ["", "apps", "extensions", "admissionregistration.k8s.io"]
  resources: ["secrets", "configmaps", "deployments", "services", "mutatingwebhookconfigurations"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cmk.fullname" . }}-role-binding-daemonset
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cmk.fullname" . }}-daemonset-controller
subjects:
- kind: ServiceAccount
  name: {{ include "cmk.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cmk.fullname" . }}-role-binding-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node
subjects:
- kind: ServiceAccount
  name: {{ include "cmk.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cmk.fullname" . }}-role-binding-tpr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cmk.fullname" . }}-third-party-resource-controller
subjects:
- kind: ServiceAccount
  name: {{ include "cmk.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cmk.fullname" . }}-role-binding-crd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cmk.fullname" . }}-custom-resource-definition-controller
subjects:
- kind: ServiceAccount
  name: {{ include "cmk.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cmk.fullname" . }}-role-binding-version
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cmk.fullname" . }}-version-controller
subjects:
- kind: ServiceAccount
  name: {{ include "cmk.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cmk.fullname" . }}-role-binding-webhook-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cmk.fullname" . }}-webhook-installer
subjects:
- kind: ServiceAccount
  name: {{ include "cmk.fullname" . }}
  namespace: {{ .Release.Namespace }}
