apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cdi-operator
  labels:
    {{- include "cdi-operator.labels" . | nindent 4 }}
    operator.cdi.kubevirt.io: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cdi-operator-cluster
subjects:
- kind: ServiceAccount
  name: {{ include "cdi-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
