apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cdi-operator
  labels:
    {{- include "cdi-operator.labels" . | nindent 4 }}
    cdi.kubevirt.io: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cdi-operator
subjects:
- kind: ServiceAccount
  name: {{ include "cdi-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
