apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cdi-operator.serviceAccountName" . }}
  labels:
    {{- include "cdi-operator.labels" . | nindent 4 }}
    operator.cdi.kubevirt.io: ""
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

