apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resourcebundlestates.k8splugin.io
spec:
  group: k8splugin.io
  names:
    kind: ResourceBundleState
    listKind: ResourceBundleStateList
    plural: resourcebundlestates
    singular: resourcebundlestate
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            selector:
              type: object
          required:
          - selector
          type: object
        status:
          properties:
            podStatuses:
              items:
                properties:
                  metadata:
                    type: object
                  ready:
                    type: boolean
                  status:
                    type: object
                required:
                - ready
                type: object
              type: array
            ready:
              type: boolean
            resourceCount:
              format: int32
              type: integer
            serviceStatuses:
              items:
                type: object
              type: array
          required:
          - ready
          - resourceCount
          - podStatuses
          - serviceStatuses
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
