// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sync.proto

package sync

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InstallAppRequest struct {
	AppContext           string   `protobuf:"bytes,1,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallAppRequest) Reset()         { *m = InstallAppRequest{} }
func (m *InstallAppRequest) String() string { return proto.CompactTextString(m) }
func (*InstallAppRequest) ProtoMessage()    {}
func (*InstallAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5273b98214de8075, []int{0}
}

func (m *InstallAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallAppRequest.Unmarshal(m, b)
}
func (m *InstallAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallAppRequest.Marshal(b, m, deterministic)
}
func (m *InstallAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallAppRequest.Merge(m, src)
}
func (m *InstallAppRequest) XXX_Size() int {
	return xxx_messageInfo_InstallAppRequest.Size(m)
}
func (m *InstallAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstallAppRequest proto.InternalMessageInfo

func (m *InstallAppRequest) GetAppContext() string {
	if m != nil {
		return m.AppContext
	}
	return ""
}

type InstallAppResponse struct {
	AppContextInstalled  bool     `protobuf:"varint,1,opt,name=app_context_installed,json=appContextInstalled,proto3" json:"app_context_installed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallAppResponse) Reset()         { *m = InstallAppResponse{} }
func (m *InstallAppResponse) String() string { return proto.CompactTextString(m) }
func (*InstallAppResponse) ProtoMessage()    {}
func (*InstallAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5273b98214de8075, []int{1}
}

func (m *InstallAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallAppResponse.Unmarshal(m, b)
}
func (m *InstallAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallAppResponse.Marshal(b, m, deterministic)
}
func (m *InstallAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallAppResponse.Merge(m, src)
}
func (m *InstallAppResponse) XXX_Size() int {
	return xxx_messageInfo_InstallAppResponse.Size(m)
}
func (m *InstallAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstallAppResponse proto.InternalMessageInfo

func (m *InstallAppResponse) GetAppContextInstalled() bool {
	if m != nil {
		return m.AppContextInstalled
	}
	return false
}

func init() {
	proto.RegisterType((*InstallAppRequest)(nil), "InstallAppRequest")
	proto.RegisterType((*InstallAppResponse)(nil), "InstallAppResponse")
}

func init() { proto.RegisterFile("sync.proto", fileDescriptor_5273b98214de8075) }

var fileDescriptor_5273b98214de8075 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xae, 0xcc, 0x4b,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe1, 0x12, 0xf4, 0xcc, 0x2b, 0x2e, 0x49, 0xcc,
	0xc9, 0x71, 0x2c, 0x28, 0x08, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe7, 0xe2, 0x4e,
	0x2c, 0x28, 0x88, 0x4f, 0xce, 0xcf, 0x2b, 0x49, 0xad, 0x28, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0xe2, 0x4a, 0x2c, 0x28, 0x70, 0x86, 0x88, 0x28, 0x79, 0x70, 0x09, 0x21, 0xeb, 0x2a, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x32, 0xe2, 0x12, 0x45, 0xd2, 0x16, 0x9f, 0x09, 0x51, 0x91, 0x9a,
	0x02, 0x36, 0x80, 0x23, 0x48, 0x18, 0x61, 0x80, 0x27, 0x4c, 0xca, 0xc8, 0x9e, 0x8b, 0x05, 0xe4,
	0x1a, 0x21, 0x73, 0x2e, 0x2e, 0x84, 0x89, 0x42, 0x42, 0x7a, 0x18, 0x8e, 0x92, 0x12, 0xd6, 0xc3,
	0xb4, 0x52, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x0f, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xed,
	0x39, 0x1e, 0x60, 0xd5, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SyncClient is the client API for Sync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SyncClient interface {
	// Sync
	InstallApp(ctx context.Context, in *InstallAppRequest, opts ...grpc.CallOption) (*InstallAppResponse, error)
}

type syncClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncClient(cc grpc.ClientConnInterface) SyncClient {
	return &syncClient{cc}
}

func (c *syncClient) InstallApp(ctx context.Context, in *InstallAppRequest, opts ...grpc.CallOption) (*InstallAppResponse, error) {
	out := new(InstallAppResponse)
	err := c.cc.Invoke(ctx, "/sync/InstallApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncServer is the server API for Sync service.
type SyncServer interface {
	// Sync
	InstallApp(context.Context, *InstallAppRequest) (*InstallAppResponse, error)
}

// UnimplementedSyncServer can be embedded to have forward compatible implementations.
type UnimplementedSyncServer struct {
}

func (*UnimplementedSyncServer) InstallApp(ctx context.Context, req *InstallAppRequest) (*InstallAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstallApp not implemented")
}

func RegisterSyncServer(s *grpc.Server, srv SyncServer) {
	s.RegisterService(&_Sync_serviceDesc, srv)
}

func _Sync_InstallApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServer).InstallApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sync/InstallApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServer).InstallApp(ctx, req.(*InstallAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sync",
	HandlerType: (*SyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstallApp",
			Handler:    _Sync_InstallApp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sync.proto",
}
