/*
 * Copyright 2020 Intel Corporation, Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controller.proto

package controller

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContextUpdateRequest struct {
	IntentGroup          string   `protobuf:"bytes,1,opt,name=intent_group,json=intentGroup,proto3" json:"intent_group,omitempty"`
	AppContext           string   `protobuf:"bytes,2,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContextUpdateRequest) Reset()         { *m = ContextUpdateRequest{} }
func (m *ContextUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*ContextUpdateRequest) ProtoMessage()    {}
func (*ContextUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{0}
}

func (m *ContextUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContextUpdateRequest.Unmarshal(m, b)
}
func (m *ContextUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContextUpdateRequest.Marshal(b, m, deterministic)
}
func (m *ContextUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContextUpdateRequest.Merge(m, src)
}
func (m *ContextUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_ContextUpdateRequest.Size(m)
}
func (m *ContextUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContextUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContextUpdateRequest proto.InternalMessageInfo

func (m *ContextUpdateRequest) GetIntentGroup() string {
	if m != nil {
		return m.IntentGroup
	}
	return ""
}

func (m *ContextUpdateRequest) GetAppContext() string {
	if m != nil {
		return m.AppContext
	}
	return ""
}

type ContextUpdateResponse struct {
	AppContextUpdated    bool     `protobuf:"varint,1,opt,name=app_context_updated,json=appContextUpdated,proto3" json:"app_context_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContextUpdateResponse) Reset()         { *m = ContextUpdateResponse{} }
func (m *ContextUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*ContextUpdateResponse) ProtoMessage()    {}
func (*ContextUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{1}
}

func (m *ContextUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContextUpdateResponse.Unmarshal(m, b)
}
func (m *ContextUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContextUpdateResponse.Marshal(b, m, deterministic)
}
func (m *ContextUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContextUpdateResponse.Merge(m, src)
}
func (m *ContextUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_ContextUpdateResponse.Size(m)
}
func (m *ContextUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContextUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContextUpdateResponse proto.InternalMessageInfo

func (m *ContextUpdateResponse) GetAppContextUpdated() bool {
	if m != nil {
		return m.AppContextUpdated
	}
	return false
}

type InstallAppRequest struct {
	AppContext           string   `protobuf:"bytes,1,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallAppRequest) Reset()         { *m = InstallAppRequest{} }
func (m *InstallAppRequest) String() string { return proto.CompactTextString(m) }
func (*InstallAppRequest) ProtoMessage()    {}
func (*InstallAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{2}
}

func (m *InstallAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallAppRequest.Unmarshal(m, b)
}
func (m *InstallAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallAppRequest.Marshal(b, m, deterministic)
}
func (m *InstallAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallAppRequest.Merge(m, src)
}
func (m *InstallAppRequest) XXX_Size() int {
	return xxx_messageInfo_InstallAppRequest.Size(m)
}
func (m *InstallAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstallAppRequest proto.InternalMessageInfo

func (m *InstallAppRequest) GetAppContext() string {
	if m != nil {
		return m.AppContext
	}
	return ""
}

type InstallAppResponse struct {
	AppContextInstalled  bool     `protobuf:"varint,1,opt,name=app_context_installed,json=appContextInstalled,proto3" json:"app_context_installed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallAppResponse) Reset()         { *m = InstallAppResponse{} }
func (m *InstallAppResponse) String() string { return proto.CompactTextString(m) }
func (*InstallAppResponse) ProtoMessage()    {}
func (*InstallAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{3}
}

func (m *InstallAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallAppResponse.Unmarshal(m, b)
}
func (m *InstallAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallAppResponse.Marshal(b, m, deterministic)
}
func (m *InstallAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallAppResponse.Merge(m, src)
}
func (m *InstallAppResponse) XXX_Size() int {
	return xxx_messageInfo_InstallAppResponse.Size(m)
}
func (m *InstallAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstallAppResponse proto.InternalMessageInfo

func (m *InstallAppResponse) GetAppContextInstalled() bool {
	if m != nil {
		return m.AppContextInstalled
	}
	return false
}

func init() {
	proto.RegisterType((*ContextUpdateRequest)(nil), "ContextUpdateRequest")
	proto.RegisterType((*ContextUpdateResponse)(nil), "ContextUpdateResponse")
	proto.RegisterType((*InstallAppRequest)(nil), "InstallAppRequest")
	proto.RegisterType((*InstallAppResponse)(nil), "InstallAppResponse")
}

func init() {
	proto.RegisterFile("controller.proto", fileDescriptor_ed7f10298fa1d90f)
}

var fileDescriptor_ed7f10298fa1d90f = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x1b, 0x06, 0x04, 0x57, 0x86, 0xf6, 0x42, 0x50, 0xd5, 0x05, 0xf0, 0xc4, 0xe4, 0xa1,
	0x20, 0x31, 0x57, 0x1d, 0x4a, 0xd7, 0x48, 0x2c, 0x2c, 0x91, 0x69, 0x2c, 0x54, 0xc9, 0xb2, 0x0f,
	0xfb, 0x22, 0xf1, 0x1b, 0xf8, 0xd5, 0x08, 0xbb, 0xad, 0xa3, 0xa6, 0xeb, 0xdd, 0xbd, 0xf7, 0x3d,
	0x3f, 0xc3, 0x64, 0xeb, 0x2c, 0x7b, 0x67, 0x8c, 0xf6, 0x92, 0xbc, 0x63, 0x27, 0x3e, 0xe0, 0x76,
	0xe5, 0x2c, 0xeb, 0x1f, 0x7e, 0xa7, 0x56, 0xb1, 0xae, 0xf5, 0x77, 0xa7, 0x03, 0xe3, 0x23, 0xdc,
	0xec, 0x2c, 0x6b, 0xcb, 0xcd, 0x97, 0x77, 0x1d, 0xcd, 0x8a, 0x87, 0xe2, 0xe9, 0xba, 0x1e, 0xa7,
	0xd9, 0xfa, 0x7f, 0x84, 0xf7, 0x30, 0x56, 0x44, 0xcd, 0x36, 0xc9, 0x67, 0x17, 0xf1, 0x02, 0x14,
	0xd1, 0xde, 0x50, 0xac, 0xa1, 0x3a, 0xf1, 0x0e, 0xe4, 0x6c, 0xd0, 0x28, 0xa1, 0xec, 0x29, 0x9b,
	0x2e, 0x6e, 0xdb, 0xc8, 0xb8, 0xaa, 0xa7, 0xd9, 0x21, 0xc9, 0x5a, 0xf1, 0x02, 0xd3, 0x8d, 0x0d,
	0xac, 0x8c, 0x59, 0x12, 0x1d, 0x12, 0x9e, 0xe0, 0x8b, 0x01, 0xfe, 0x0d, 0xb0, 0xaf, 0xda, 0xb3,
	0x17, 0x50, 0xf5, 0xd9, 0xbb, 0x74, 0x71, 0xa4, 0x97, 0xd9, 0x60, 0x73, 0x58, 0x2d, 0x7e, 0x0b,
	0x80, 0xdc, 0x1c, 0xae, 0x60, 0x92, 0x92, 0x2d, 0x8f, 0xb7, 0x58, 0xc9, 0x73, 0x35, 0xce, 0xef,
	0xe4, 0xd9, 0x06, 0xc4, 0x08, 0x5f, 0x01, 0x72, 0x3a, 0x44, 0x39, 0x78, 0xe0, 0xbc, 0x94, 0xc3,
	0xf8, 0x62, 0xf4, 0x79, 0x19, 0x3f, 0xee, 0xf9, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x09, 0xa2, 0x85,
	0x59, 0xcc, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControllerClient interface {
	// Controllers
	UpdateAppContext(ctx context.Context, in *ContextUpdateRequest, opts ...grpc.CallOption) (*ContextUpdateResponse, error)
	// Sync
	InstallApp(ctx context.Context, in *InstallAppRequest, opts ...grpc.CallOption) (*InstallAppResponse, error)
}

type controllerClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerClient(cc grpc.ClientConnInterface) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) UpdateAppContext(ctx context.Context, in *ContextUpdateRequest, opts ...grpc.CallOption) (*ContextUpdateResponse, error) {
	out := new(ContextUpdateResponse)
	err := c.cc.Invoke(ctx, "/controller/UpdateAppContext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) InstallApp(ctx context.Context, in *InstallAppRequest, opts ...grpc.CallOption) (*InstallAppResponse, error) {
	out := new(InstallAppResponse)
	err := c.cc.Invoke(ctx, "/controller/InstallApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
type ControllerServer interface {
	// Controllers
	UpdateAppContext(context.Context, *ContextUpdateRequest) (*ContextUpdateResponse, error)
	// Sync
	InstallApp(context.Context, *InstallAppRequest) (*InstallAppResponse, error)
}

// UnimplementedControllerServer can be embedded to have forward compatible implementations.
type UnimplementedControllerServer struct {
}

func (*UnimplementedControllerServer) UpdateAppContext(ctx context.Context, req *ContextUpdateRequest) (*ContextUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAppContext not implemented")
}
func (*UnimplementedControllerServer) InstallApp(ctx context.Context, req *InstallAppRequest) (*InstallAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstallApp not implemented")
}

func RegisterControllerServer(s *grpc.Server, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_UpdateAppContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).UpdateAppContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller/UpdateAppContext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).UpdateAppContext(ctx, req.(*ContextUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_InstallApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).InstallApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller/InstallApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).InstallApp(ctx, req.(*InstallAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Controller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateAppContext",
			Handler:    _Controller_UpdateAppContext_Handler,
		},
		{
			MethodName: "InstallApp",
			Handler:    _Controller_InstallApp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller.proto",
}
