apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubevirt-operator
  labels:
    {{- include "kubevirt-operator.labels" . | nindent 4 }}
    kubevirt.io: ""
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - delete
