apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubevirt-operator.serviceAccountName" . }}
  labels:
    {{- include "kubevirt-operator.labels" . | nindent 4 }}
    kubevirt.io: ""
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
