kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.config.name }}
  labels:
    {{- include "multus.labels" . | nindent 4 }}
    tier: node
data:
  cni-conf.json: | {{ .Values.config.data | toPrettyJson | nindent 4}}
