---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dummy
data:
  key1: value1
---
{{ if .Values.goingEmpty }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
spec:
  template:
    metadata:
      labels:
        app: dummy
    spec:
      container:
      - name: dummy
        image: dummy
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: dummy
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: dummy
