# Resources to create ONAP4K8s v2 Microservices
---
# Orchestrator Config Map
kind: ConfigMap
apiVersion: v1
metadata:
  name: orchestrator
  labels:
    app: orchestrator
data:
  config.json: |
          {
          "database-type": "mongo",
          "database-ip": "mongo",
          "etcd-ip": "etcd",
          "service-port": "9015"
          }

---
# Orchestrator Service
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  labels:
    app: orchestrator
spec:
  selector:
    app: orchestrator
  type: NodePort
  ports:
  - name: http
    port: 9015
    protocol: TCP
    targetPort: 9015

---
# Orchestrator Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: rtsood/mco:0.0.1
          imagePullPolicy: IfNotPresent
          command: ["/opt/mco/entrypoint", "mco"]
          workingDir: /opt/mco
          ports:
          - containerPort: 9015
          volumeMounts:
          - name: config
            mountPath: /opt/mco/config.json
            subPath: config.json
      volumes:
        - name: config
          configMap:
            name: orchestrator
            items:
            - key: config.json
              path: config.json

---
# NCM Config Map
kind: ConfigMap
apiVersion: v1
metadata:
  name: ncm
  labels:
    app: ncm
data:
  config.json: |
          {
          "database-type": "mongo",
          "database-ip": "mongo",
          "etcd-ip": "etcd",
          "service-port": "9031"
          }

---
# NCM Service
apiVersion: v1
kind: Service
metadata:
  name: ncm
  labels:
    app: ncm
spec:
  selector:
    app: ncm
  type: NodePort
  ports:
  - name: internal
    port: 9033
    protocol: TCP
    targetPort: 9033
  - name: http
    port: 9031
    protocol: TCP
    targetPort: 9031

---
# NCM Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ncm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ncm
  template:
    metadata:
      labels:
        app: ncm
    spec:
      containers:
        - name: ncm
          image: rtsood/mco:0.0.1
          imagePullPolicy: IfNotPresent
          command: ["/opt/mco/entrypoint", "ncm"]
          workingDir: /opt/mco
          ports:
          - containerPort: 9033
          - containerPort: 9031
          volumeMounts:
          - name: config
            mountPath: /opt/mco/config.json
            subPath: config.json
      volumes:
        - name: config
          configMap:
            name: ncm
            items:
            - key: config.json
              path: config.json

---
# RSYNC ConfigMap
kind: ConfigMap
apiVersion: v1
metadata:
  name: rsync
  labels:
    app: rsync
data:
  config.json: |
          {
          "database-type": "mongo",
          "database-ip": "mongo",
          "etcd-ip": "etcd",
          "service-port": "9041"
          }

---
# RSYNC Service
apiVersion: v1
kind: Service
metadata:
  name: rsync
  labels:
    app: rsync
spec:
  selector:
    app: rsync
  type: NodePort
  ports:
  - name: internal
    port: 9041
    protocol: TCP
    targetPort: 9041

---
# RSYNC Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsync
  template:
    metadata:
      labels:
        app: rsync
    spec:
      containers:
        - name: rsync
          image: rtsood/mco:0.0.1
          imagePullPolicy: IfNotPresent
          command: ["/opt/mco/entrypoint", "rsync"]
          workingDir: /opt/mco
          ports:
          - containerPort: 9041
          volumeMounts:
          - name: config
            mountPath: /opt/mco/config.json
            subPath: config.json
      volumes:
        - name: config
          configMap:
            name: rsync
            items:
            - key: config.json
              path: config.json

