---
#- name: install epel-release on Red Hat based OS
#  yum: name=epel-release
#  when: ansible_os_family == 'RedHat'
#
#- name : install dependencies
#  include_role:
#    name: install-dependencies
#
#- name: install Python dependencies
#  pip:
#    name:
#      - setuptools
#      - docker
#
- name: clone CMK repository
  git:
    repo: "{{ cmk_git_url }}"
    dest: "{{ cmk_dir }}"
    version: "{{ cmk_version }}"
    force: yes

- name: read current CMK version
#  command: git describe --abbrev=0 --tags
  command: echo v1.4.1
  args:
    chdir: "{{ cmk_dir }}"
  register: cmk_img_version

- name: build CMK image
  make:
    chdir: "{{ cmk_dir }}"

- name: tag CMK image
  command: docker tag cmk:{{ cmk_img_version.stdout }} {{ registry_local_address }}/cmk:{{ cmk_img_version.stdout }}

#- name: push CMK image to local registry
#  command: docker push {{ registry_local_address }}/cmk:{{ cmk_img_version.stdout }}
#  when:
#    - inventory_hostname == groups['kube-node'][0]

- name: create Helm charts directory if needed
  file:
    path: /tmp/charts
    state: directory
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: copy CMK Helm chart to the master node
  copy:
    src: "{{ role_path }}/charts/cpu-manager-for-kubernetes"
    dest: "/tmp/charts/"
  when:
    - inventory_hostname == groups['kube-master'][0]

# adds all kube-nodes to the list of CMK nodes
- name: build list of CMK hosts
  set_fact:
    cmk_hosts_list: "{{ groups['cmk'] | join(',') }}"
  when:
    - cmk_use_all_hosts != true
    - (cmk_hosts_list is undefined) or (cmk_hosts_list | length == 0)

- name: set values for CMK Helm chart values
  set_fact:
    cmk_image: "{{ registry_local_address }}/cmk"
    cmk_tag: "{{ cmk_img_version.stdout }}"
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: populate CMK Helm chart values template and push to master node
  template:
    src: "helm_values.yml.j2"
    dest: "/tmp/charts/cmk-values.yml"
    force: yes
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: install CMK helm chart
  command: helm upgrade --install cmk --namespace {{ cmk_namespace }} -f /tmp/charts/cmk-values.yml /tmp/charts/cpu-manager-for-kubernetes
  when:
    - inventory_hostname == groups['kube-master'][0]

## this will mean that nodes are ready to be untainted
#- name: wait for all cmk daemonset pods to be running
#  shell: kubectl get pods -n {{ cmk_namespace }} -l name=cmk -o jsonpath={.items[*].status.phase}
#  register: kubectl_cmk_running
#  until: "['Running'] == kubectl_cmk_running.stdout.split() | unique"
#  retries: 24
#  delay: 5
#  when:
#    - inventory_hostname in cmk_hosts_list.split(',')
#    - cmk_untaint_nodes
#  delegate_to: "{{ groups['kube-master']|first }}"
#  failed_when: false
#
#- name: untaint nodes
#  command: kubectl taint node "{{ inventory_hostname }}" cmk-
#  failed_when: false
#  register: untaint_result
#  changed_when: "untaint_result.rc == 0"
#  when:
#    - inventory_hostname in cmk_hosts_list.split(',')
#    - cmk_untaint_nodes
#  delegate_to: "{{ groups['kube-master']|first }}"
