{{ if .Values.persistence.enabled }}
{{- $root := . -}}
{{ range $i, $e := until (int $root.Values.replicaCount) }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "common.fullname" $root }}-data-{{ $i }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    type: {{ $root.Values.persistence.storageType }}
    app: {{ include "common.fullname" $root }}
    chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  capacity:
    storage: {{ $root.Values.persistence.storage }}
  accessModes:
    - {{ $root.Values.persistence.accessMode }}
  storageClassName: "{{ include "common.fullname" $root }}-data"
  hostPath:
    path: {{ $root.Values.persistence.mountPath }}/{{ $root.Release.Name }}/{{ $root.Values.persistence.mountSubPath }}-{{ $i }}
  persistentVolumeReclaimPolicy: {{ $root.Values.persistence.volumeReclaimPolicy }}
{{ end }}
{{ end }}

