FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y \
        bc \
        build-essential \
        curl \
        kmod \
        libelf-dev \
        libssl-dev \
        libudev-dev \
        pciutils \
        pkg-config \
        && \
    rm -rf /var/lib/apt/lists/*

COPY _common.sh /
COPY entrypoint-iavf-driver-installer.sh /entrypoint.sh

CMD /entrypoint.sh
