apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: '{{ .Values.global.ovnMultusNetworkName }}'
spec:
  config: '{
     "cniVersion": "0.3.1",
     "name": "ovn4nfv-k8s-demoplugin",
     "type": "ovn4nfvk8s-cni"
  }'
