apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.global.onapPrivateNetworkName }}
spec:
  cnitype : ovn4nfvk8s
  name: {{ .Values.global.onapPrivateNetworkName }} 
  subnet: {{ .Values.global.onapPrivateNetCidr }}
  gateway: {{ .Values.global.onapPrivateNetGw }}
