apiVersion: v1
kind: onapNetwork
metadata:
  name: {{ .Values.network.protectedNetworkName }}
  cnitype : ovn4nfvk8s
spec:
  name: {{ .Values.network.protectedNetworkName }}
  subnet: {{ .Values.network.protectedNetCidr }}
  gateway: {{ .Values.network.protectedNetGw }}/{{ .Values.gatewayVarible }}
