apiVersion: k8s.plugin.opnfv.org/v1alpha1
kind: Network
metadata:
  name: {{ .Values.global.protectedNetworkName }}
spec:
  cniType : ovn4nfv
  ipv4Subnets:
  - name: subnet1
    subnet: {{ .Values.global.protectedNetCidr }}
    gateway: {{ .Values.global.protectedNetGw }}
