---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: flannel-vm
  namespace: kube-system
spec:
  config: '{
            "cniVersion": "0.3.1",
            "name" : "cni0",
            "plugins": [ {
              "type": "flannel",
              "cniVersion": "0.3.1",
              "masterplugin": true,
              "delegate": {
                  "isDefaultGateway": true
              }
            },
            {
              "type": "tuning"
            }]
          }'

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bpa-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: bpa-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - namespaces
  - jobs
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - bpa-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - bpa.akraino.org
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts
  verbs:
  - '*'
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bpa-operator
subjects:
- kind: ServiceAccount
  name: bpa-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: bpa-operator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: provisionings.bpa.akraino.org
spec:
  group: bpa.akraino.org
  names:
    kind: Provisioning
    listKind: ProvisioningList
    plural: provisionings
    singular: provisioning
    shortNames:
    - bpa
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: softwares.bpa.akraino.org
spec:
  group: bpa.akraino.org
  names:
    kind: Software
    listKind: SoftwareList
    plural: softwares
    singular: software
    shortNames:
    - sw
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpa-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bpa-operator
  template:
    metadata:
      labels:
        name: bpa-operator
    spec:
      hostNetwork: true
      serviceAccountName: bpa-operator
      containers:
        - name: bpa-operator
          # Replace this with the built image name
          image: ramay1/bpa-operator:v0.1.0-tp
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: dhcp-shared
            mountPath: /var/lib/dhcp/
          - name: icn-cluster
            mountPath: /multi-cluster
          command:
          - /bpa-operator
          securityContext:
            privileged: true
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "bpa-operator"
      volumes:
      - name: dhcp-shared
        hostPath:
          path: /opt/icn/dhcp/
      - name: icn-cluster
        hostPath:
          path: /opt/kud/multi-cluster
