# Default values for cnf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  name: sdewan-cnf
  namespace: default
  labels: sdewan-cnf

spec:
  progressDeadlineSeconds: 600
  replicas: 1

strategy:
  maxSurge: 25%
  maxUnavailable: 25%

nfn:
  - defaultGateway: false
    interface: net2
    ipAddress: 10.10.10.15
    name: pnetwork
    separate: ","
  - defaultGateway: false
    interface: net0
    ipAddress: 172.16.30.10
    name: ovn-network
    separate: ""

containers:
  image: integratedcloudnative/openwrt:0.3.0
  imagePullPolicy: IfNotPresent
  name: sdewan

labelName: "node-role.kubernetes.io/master"
labelValue: ""

restartPolicy: Always
