build:
	$(MAKE) -C monitor build
	$(MAKE) -C k8splugin build

deploy:
	$(MAKE) -C monitor deploy
	$(MAKE) -C k8splugin deploy

all:
	$(MAKE) -C monitor all
	$(MAKE) -C k8splugin all

clean:
	$(MAKE) -C monitor clean
	$(MAKE) -C k8splugin clean
