apiVersion: v1
kind: Service
metadata:
  name: testchart2
  labels:
    chart: "testchart2-0.1.0"
    namespace: "testnamespace"
    release-name: "testreleasename"
    release-is-upgrade: "false"
    release-is-install: "true"
    kube-version/major: "1"
    kube-version/minor: "14"
    kube-version/gitversion: "v1.14.0"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: nginx
  selector:
    app: testchart2