apiVersion: v1
kind: Service
metadata:
  name: nfn-operator
  labels:
    {{- include "ovn4nfv.labels" . | nindent 4 }}
    role: nfn-operator
spec:
  type: {{ .Values.nfnOperator.service.type }}
  ports:
  - port: {{ .Values.nfnOperator.service.port }}
    protocol: TCP
    targetPort: 50000
  selector:
    {{- include "ovn4nfv.selectorLabels" . | nindent 4 }}
    role: nfn-operator
