nameOverride: ""

policies:
- # policyName is the name of the policy
  policyName: "policy-xl710"

  # nicSelector selects the NICs to be configured.  At least one of
  # vendor, deviceId, pfNames, or rootDevices must be deined.
  nicSelector:
    # deviceID is the device hex code of SR-IOV device.
    deviceID: "1583"

    # netFilter is the infrastructure networking selection
    # filter. Allowed values are
    # "openstack/NetworkID:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    #netFilter: ""

    # pfNames is a list of the SR-IOV PF names.
    #pfNames: []

    # rootDevices is a list of the PCI addresses of SR-IOV PFs.
    #rootDevices: []

    # vendor is the vendor hex code of SR-IOV device. Allowed values are
    # "8086", "15b3".
    vendor: "8086"

  # nodeSelector selects the nodes to be configured.
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
    feature.node.kubernetes.io/pci-0200_8086_1583.present: "true"

  # numVfs is the Number of VFs for each PF
  numVfs: 8

  # resourceName is the SR-IOV Network device plugin endpoint.
  resourceName: "intel_sriov_nic"

- policyName: "policy-82599es"
  nicSelector:
    deviceID: "10fb"
    vendor: "8086"
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
    feature.node.kubernetes.io/pci-0200_8086_10fb.present: "true"
  numVfs: 8
  resourceName: "intel_sriov_nic"

- policyName: "policy-i350"
  nicSelector:
    deviceID: "1521"
    vendor: "8086"
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
    feature.node.kubernetes.io/pci-0200_8086_1521.present: "true"
  numVfs: 2
  resourceName: "intel_sriov_nic"

networks:
- # networkName is the name of both the SriovNetwork and the created
  # NetworkAttachmentDefinition custom resource.
  networkName: "sriov-intel"

  # networkNamespace of the NetworkAttachmentDefinition custom resource.
  networkNamespace: "default"

  # ipam configuration to be used for the network.
  ipam: |
    {
      "type": "host-local",
      "subnet": "10.56.206.0/24",
      "routes": [{
        "dst": "0.0.0.0/0"
      }],
      "gateway": "10.56.206.1"
    }

  #
  # Optional values are listed below.
  #

  # deviceType is the driver type for configured VFs. Allowed values are
  # "netdevice" and "vfio-pci".
  #deviceType: "netdevice"

  # eSwitchMode NIC Device Mode. Allowed values are "legacy" and
  # "switchdev".
  #eSwitchMode: "switchdev"

  # isRdma defaults to false.
  #isRdma: true

  # linkType is the NIC link type. Allowed values are "eth", "ETH",
  # "ib", and "IB".
  #linkType: "eth"

  # mtu of VF
  #mtu: 9000

  # priority of the policy, higher priority policies can override lower
  # ones.
  #priority: 99

  # capabilities to be configured for this network. Capabilities
  # supported: (mac|ips), e.g. '{"mac": true}'
  #capabilities: |
  #  {
  #    "mac": true
  #  }

  # linkState of VF (enable|disable|auto).
  #linkState: "enable"

  # maxTxRate, in Mbps, for the VF. Defaults to 0 (no rate limiting).
  #maxTxRate: 0

  # metaPlugins configuration to be used in order to chain metaplugins
  # to the SR-IOV interface returned by the operator.
  #metaPlugins: |
  #  {
  #    "type": "tuning",
  #    "sysctl": {
  #      "net.core.somaxconn": "500"
  #    }
  #  }

  # minTxRate, in Mbps, for the VF. Defaults to 0 (no rate
  # limiting). min_tx_rate should be <= max_tx_rate.
  #minTxRate: 0

  # spoofChk for VF, (on|off)
  #spoofChk: "off"

  # trust mode of VF (on|off)
  #trust: "off"

  # vlan ID to assign for the VF. Defaults to 0.
  #vlan: 0

  # vlanQoS ID to assign for the VF. Defaults to 0.
  #vlanQoS: 0

  # resourceName is the SR-IOV Network device plugin endpoint.
  resourceName: "intel_sriov_nic"
