apiVersion: v1
kind: Service
metadata:
  name: sink-service
  labels:
    app.kubernetes.io/name: {{ include "packetgen.name" . }}
    helm.sh/chart: {{ include "packetgen.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.port  }}
      nodePort: {{ .Values.service.ports.nodePort }} 
  selector:
    app.kubernetes.io/name: {{ include "packetgen.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: vFirewall
    context: darkstat
