apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "qat-device-plugin.fullname" . }}
  labels:
    {{- include "qat-device-plugin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "qat-device-plugin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "qat-device-plugin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: intel-qat-kernel-plugin
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        env:
        - name: VERBOSITY
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.config.name }}
              key: VERBOSITY
        args: ["-mode", "kernel", "-v", "$(VERBOSITY)"]
        volumeMounts:
        - name: devfs
          mountPath: /dev
        - name: etcdir
          mountPath: /etc
          readOnly: true
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: etcdir
        hostPath:
          path: /etc
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: devfs
        hostPath:
          path: /dev
